version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: dus_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./infrastructure/mongo/init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    command: ['--replSet', 'rs0', '--bind_ip_all']
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: dus_redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
